### PR TITLE
Update std::io as per latest rust changes.

### PR DESCRIPTION
**Pull request by afaur**
Change std::io imports to std::old_io as per latest rust changes.

### CODE REVIEW

**Comment by kjpgit** [comment]
thanks, I made a nightly branch, updated the readme, and did the replace.   going to be a bumpy ride until beta, I think.

**Comment by afaur** [comment]
Sorry, didn't realize you didn't want contributors on this.  Good work, and good luck with your project.

**Comment by kjpgit** [comment]
sorry, I must have broken some github netiquette - I'm new to this.  You had unrelated whitespace changes in your patch so I didn't merge it as is.

**Comment by kjpgit** [comment]
there, I put your authorship in the commit: https://github.com/kjpgit/mudpie/commit/c8667ee03d8e76e5be979ea33350e857d4a0fb27

**Comment by afaur** [comment]
@kjpgit 
Thanks, I do appreciate that.  The whitespace changes were not intended to be in the patch.  If you would like me to remove them next time let me know.  My editor does that automatically (with the vim configuration I use) and I had neglected to notice that.  

If you wouldn't mind I would like to add an issue to add travis-ci to the project.  I have seen some rust projects using it.  What it could do is download the nightly rust version, and cargo build the project in a virtual machine and show the status on the github project page.  This would add an early warning system when breaking changes come in and maybe someone can see that and help out.

**Comment by kjpgit** [comment]
I looked at travis-ci because I liked the automatic doc building but it
seemed to require a ton of github permissions I was uncomfortable with (I
think it required write access to the repo). If that's not the case I
wouldn't mind using it.

**Comment by bayleedev** [comment]
@kjpgit the only write travis needs is to write web hooks, everything else is read. You should be good to go! :D

**Pull request closed without merging**
